version: 2
updates:
- package-ecosystem: docker
  directory: "/devenv/web/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
- package-ecosystem: yarn
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
