inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
  - rubocop-rails
Style/AsciiComments:
      Enabled: false
Metrics/BlockLength:
  Max: 27
  Exclude:
    - 'spec/**/*'
AllCops:
  NewCops: enable
  SuggestExtensions: false

RSpec/ContextWording:
  AllowedPatterns:
    - "^when"
    - "^if"
    # Suffix pattern for japanese
    - "時$"
    - "とき$"
    - "場合$"

RSpec/ExampleLength:
  Enabled: false

Lint/AssignmentInCondition:
  Exclude:
    - 'db/migrate/20210111023112_add_service_name_to_active_storage_blobs.active_storage.rb'

Metrics/AbcSize:
  Max: 19

Metrics/MethodLength:
  Max: 18

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/20210111023112_add_service_name_to_active_storage_blobs.active_storage.rb'

Rails/NotNullColumn:
  Exclude:
    - 'db/migrate/20190612123743_add_user_id_to_tasks.rb'

