inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
  - rubocop-rails
Style/AsciiComments:
      Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
AllCops:
  NewCops: enable
  SuggestExtensions: false

RSpec/ContextWording:
  AllowedPatterns:
    - "^when"
    - "^if"
    # Suffix pattern for japanese
    - "時$"
    - "とき$"
    - "場合$"
