plugins:
  - rubocop-rspec
  - rubocop-rails
Style/AsciiComments:
      Enabled: false
AllCops:
  NewCops: enable
  SuggestExtensions: false

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'

Layout/LineLength:
  Max: 190
  Exclude:
    - 'bin/bundle'

Style/MixinUsage:
  Exclude:
    - 'bin/update'

Metrics/BlockLength:
  Max: 27
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/20210111023113_create_active_storage_variant_records.active_storage.rb'

RSpec/ContextWording:
  AllowedPatterns:
    - "^when"
    - "^if"
    # Suffix pattern for japanese
    - "時$"
    - "とき$"
    - "場合$"

RSpec/ExampleLength:
  Enabled: false

Lint/AssignmentInCondition:
  Exclude:
    - 'db/migrate/20210111023112_add_service_name_to_active_storage_blobs.active_storage.rb'

Metrics/AbcSize:
  Max: 19

Metrics/MethodLength:
  Max: 18

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/20210111023112_add_service_name_to_active_storage_blobs.active_storage.rb'

Rails/NotNullColumn:
  Exclude:
    - 'db/migrate/20190612123743_add_user_id_to_tasks.rb'

Style/GuardClause:
  Exclude:
    - 'db/migrate/20210111023112_add_service_name_to_active_storage_blobs.active_storage.rb'

Style/Documentation:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 9

RSpec/NestedGroups:
  Max: 4
