version: '3'
services:
  web: &app_base
    #image: 'cimg/ruby:3.0.3-browsers'
    build:
      context: .
      dockerfile: ./devenv/web/Dockerfile
      args:
        IMAGE_FILE: ${IMAGE_FILE:-ruby}
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    # platform: linux/x86_64
    environment:
      IMAGE_FILE: ${IMAGE_FILE:-ruby}
      PGSQL_HOST: pgsql
      DATABASE_USER: postgres
      POSTGRES_PASSWORD: secret
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      BOOTSNAP_CACHE_DIR: '/usr/local/bundle'
      HISTFILE: '/work/app/log/.bash_history'
      TZ: 'Asia/Tokyo'
      RAILS_ENV: ${RAILS_ENV:-development}
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub    #追加、どのコンテナのブラウザを使用するか指定
    volumes:
      - .:/work/app:cached
      - rails_cache:/work/app/tmp/cache
      - bundler:/usr/local/bundle
      # exclude volumes
      - /work/app/vendor
      - /work/app/tmp
      - /work/app/log
      - /work/app/.git
      - /work/app/node_modules
    working_dir: /work/app
    user: root
    ports:
      - "13000:3000"
    depends_on:
      - pgsql
      - redis
      - chrome
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
  chrome:
    build:
      context: .
      dockerfile: ./devenv/chrome/Dockerfile
      args:
        CHROME_IMAGE: ${CHROME_IMAGE:-selenium/standalone-chrome}
      # image: selenium/standalone-chrome:latest
    ports:
      - '4444:4444'

  redis:
    image: redis:7-alpine
    ports:
      - "16379:6379"
#    command: redis-server --appendonly yes --requirepass foobared
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 50080:1080
  pgsql:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  bundler:
  rails_cache:
  redis-data:
    driver: local
