version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./devenv/web/Dockerfile
    command: foreman start
    environment:
      PGSQL_HOST: pgsql
      DATABASE_USER: postgres
      POSTGRES_PASSWORD: secret
      REDIS_URL: redis://redis:6379
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - .:/myapp
      - bundler:/usr/local/bundle
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - pgsql
      - redis
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
#    command: redis-server --appendonly yes --requirepass foobared
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 50080:1080
  pgsql:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  bundler: {}
  redis-data:
    driver: local
