version: 2
jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers-legacy
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
          LANG: ja_JP.UTF-8
          LC_ALL: C.UTF-8
          LANGUAGE: ja_JP.UTF-8
          CIRCLE_ARTIFACTS: /tmp/artifacts
      - image: circleci/postgres:11.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: taskleaf_test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # Yarn Setup
      - restore_cache:
          keys:
            - taskleaf-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      # Database setup
      - run: mv config/database.yml.ci config/database.yml
      - run: bin/rails db:create
      - run: bin/rails db:schema:load
      - type: shell
        command: bundle exec brakeman
      # Run rspec
      - type: shell
        command: bundle exec rspec
      # Rubocop
      - run:
          name: Rubocop
          command: bundle exec rubocop

  rspec:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers-legacy
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec
#  continuous_bundle_update:
#    docker:
#      - image: circleci/ruby:2.6.5-node
#    steps:
#      - checkout
#      - restore_cache:
#          name: Restore bundler cache
#          key: taskleaf-{{ checksum "Gemfile.lock" }}
#      - run:
#          name: Setup requirements for continuous bundle update
#          command: gem install -N circleci-bundle-update-pr
#      - deploy:
#          name: Continuous bundle update
#          command: circleci-bundle-update-pr $GIT_USER_NAME $GIT_USER_EMAIL develop
  actions-package-update: # TODO Github Actionsが利用可能になったら移行したい
    docker:
      - image: node:10-alpine
    steps:
      - run: apk add --update --no-cache git openssh-client
      - checkout
      - run: yarn global add actions-package-update
      - run: yarn install
      - run: UPDATE_COMMAND=yarn EXECUTE=true actions-package-update upgrade --latest
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *" # UTCなのでJSTだと9時
          filters:
            branches:
              only: master
    jobs:
      - actions-package-update
      # - continuous_bundle_update
  rubocop_rspec:
    jobs:
      - rubocop
      # - continuous_bundle_update
      - actions-package-update
      # - rspec:
      #   requires:
      #   - rubocop
