name: Build

#プルリクエスト作成時に実行(他にもpush時など設定できます)
on: [ pull_request ]

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  rspec_job:
    #ubuntu環境で動かします
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.2-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    #GitHub Actionsでサポートしているrubyのversionは2.6系以降です
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby version
        uses: ruby/setup-ruby@master
        with:
          ruby-version: 3.0.3

      #MySQLをインストール
      #- name: Install dependent libralies
      #  run: sudo apt-get install libmysqlclient-dev

      - name: Setup bundler
        run: gem install bundler

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: bundle install
        run: |
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: yarn install
        run: yarn install --check-files
      - name: rubocop
        run: bundle exec rubocop

      - name: Setup Database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rake db:create
          bundle exec rake db:schema:load
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      - name: Run RSpec
        run: bundle exec rspec
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
